<?php require 'templates/layout/header.phtml'; ?>
<form action="editarCategoria/<?= $categoria->ID_Categorias ?>" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" value = "<?= htmlspecialchars($categoria->Nombre) ?>" type="text" class="form-control">
            </div>
        </div>       
    </div>
    <div class="row">
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>URL de imagen:</label>
                <input required name="URL_imagen" value = "<?= htmlspecialchars($categoria->URL_imagen) ?>" type="text" class="form-control">
            </div>
        </div>
    <div class="form-group">
        <label>Descripcion</label>
        <textarea name="descripcion"  class="form-control" rows="3">"<?=  htmlspecialchars($categoria->Descripcion) ?>"</textarea>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>
<?php require 'templates/layout/footer.phtml'; ?>