<?php require 'templates/layout/header.phtml'; ?>
<form action="nuevaCategoria" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" value = "<?= $categoria->Nombre ?>" type="text" class="form-control">
            </div>
        </div>

       
    </div>
    <div class="row">
    

        </div>
        <div class="col-9">
            <div class="form-group">
                <label>URL de imagen:</label>
                <input required name="URL_imagen" value = "<?= $categoria->URL_imagen ?>" type="text" class="form-control">
            </div>
        </div>

    <div class="form-group">
        <label>Descripcion</label>
        <textarea name="descripcion"  value = "<?= $categoria->Descripcion ?>" placeholder = "<?= $categoria->Descripcion ?>" class="form-control" rows="3"></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>
<?php require 'templates/layout/footer.phtml'; ?>