<?php require 'templates/layout/header.phtml'; ?>
<form action="nuevo" method="POST" class="my-4">

    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="form-control">
            </div>
        </div>
        <div class="col-3">
            <div class="form-group">
                <label>Categoria</label>
                <select required name="categoria" class="form-control">
                    <?php foreach ($categorias as $categoria): ?>
                        <option value=<?=$categoria->ID_Categorias ?>><?=$categoria->Nombre ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
    <div class="col-6">
            <div class="form-group">
                <label>Precio</label>
                <input required name="precio" type="number" class="form-control">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label>Marca</label>
                <input required name="marca" type="text" class="form-control">
            </div>
        </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>URL de imagen:</label>
                <input required name="URL_imagen" type="text" class="form-control">
            </div>
        </div>
    <div class="form-group">
        <label>Descripcion</label>
        <textarea name="descripcion" class="form-control" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
    
</form>
<?php require 'templates/layout/footer.phtml'; ?>