<?php require 'templates/layout/header.phtml'; ?>
    <div class="container mt-5">
    <div class="row">
        <?php foreach ($productos as $producto): ?>         
            <div class="col-12 col-md-6 col-lg-4 mb-4">
                <div class="card">
                    <img src=<?=$producto->URL_imagen?> class="card-img-top" alt="Producto 1">
                    <div class="card-body">
                        <h5 class="card-title"><?= $producto->Nombre ?></h5>
                        <p class="card-text"><?= $producto->Precio ?></p>                       
                        <?php  $categoriaProducto = "Teclados";
                        foreach ($categorias as $categoria){                      
                            if ($categoria->ID_Categorias == $producto->ID_Categorias){                    
                            $categoriaProducto= $categoria->Nombre;                   
                            }                            
                        } ?>  
                        <a href="categorias/<?= $categoriaProducto ?>" ><?= $categoriaProducto ?></a>
                        <a href="<?= BASE_URL ?>productos/<?= $producto->ID_Productos ?>" class="btn btn-primary">Ver más</a>
                        <?php if ($this->user):?>
                            <a href="<?= BASE_URL ?>formEditarProducto/<?= $producto->ID_Productos ?>" class="btn btn-primary">Editar</a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>  





<?php require_once 'templates/layout/footer.phtml'; ?>