<?php require 'templates/layout/header.phtml'; ?>
    <h2>Categorias:</h2>
    <div class="container mt-5">
    <div class="row">
        <?php foreach ($categorias as $categoria): ?>
            <div class="col-12 col-md-6 col-lg-4 mb-4">
                <div class="card">
                    <img src=<?=htmlspecialchars($categoria->URL_imagen)?> class="card-img-top" alt="categoria 1">
                    <div class="card-body">
                        <h5 class="card-title"><?= htmlspecialchars($categoria->Nombre) ?></h5>                        
                        <a href="categorias/<?= htmlspecialchars($categoria->Nombre) ?>" class="btn btn-primary">Ver productos</a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<?php require 'templates/layout/footer.phtml'; ?>