<?php require 'templates/layout/header.phtml'; ?>
<?php // $categoriass = $categorias; //PREGUNTARRRRRRRRRRRRRRRRRRR?>

    <div class="container mt-5">
    <div class="row">
        <?php foreach ($productos as $producto): ?>
            <div class="col-12 col-md-6 col-lg-4 mb-4">
                <div class="card">
                    <img src=<?=$producto->URL_imagen?> class="card-img-top" alt="Producto 1">
                    <div class="card-body">
                        <h5 class="card-title"><?= $producto->Nombre ?></h5>
                        <p class="card-text"><?= $producto->Precio ?></p>
                        <a href="<?= BASE_URL ?>productos/<?= $producto->ID_Productos ?>" class="btn btn-primary">Ver más</a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>





<?php require 'templates/layout/footer.phtml'; ?>